// Generated by CoffeeScript 1.6.3
(function() {
  app.get('/login', function(req, res) {
    return res.render("views/login", {
      title: 'Login',
      stylesheet: 'login'
    });
  });

}).call(this);

/*
//@ sourceMappingURL=Routes.map
*/
