// Generated by CoffeeScript 1.6.3
(function() {
  var routes;

  routes = function(app) {
    return app.get('/login', function(req, res) {
      return res.render("" + __dirname + "\\views\\login", {
        title: 'Login',
        stylesheet: 'login'
      });
    });
  };

  module.exports = routes;

}).call(this);

/*
//@ sourceMappingURL=Routes.map
*/
